INSERT INTO PUBLIC.GENRES (GENRE) VALUES ('COMEDY');
INSERT INTO PUBLIC.GENRES (GENRE) VALUES ('DRAMA');
INSERT INTO PUBLIC.GENRES (GENRE) VALUES ('CARTOON');
INSERT INTO PUBLIC.GENRES (GENRE) VALUES ('THRILLER');
INSERT INTO PUBLIC.GENRES (GENRE) VALUES ('DOCUMENTARY');
INSERT INTO PUBLIC.GENRES (GENRE) VALUES ('ACTION');

INSERT INTO PUBLIC.MPA_RATING (RATING) VALUES ('G');
INSERT INTO PUBLIC.MPA_RATING (RATING) VALUES ('PG');
INSERT INTO PUBLIC.MPA_RATING (RATING) VALUES ('PG13');
INSERT INTO PUBLIC.MPA_RATING (RATING) VALUES ('R');
INSERT INTO PUBLIC.MPA_RATING (RATING) VALUES ('NC17');

INSERT INTO PUBLIC.FRIEND_STATUS (STATUS) VALUES ('CONFIRMED');
INSERT INTO PUBLIC.FRIEND_STATUS (STATUS) VALUES ('NOT_CONFIRMED');